/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import universidad1.Alumno;
import universidad1.AlumnoData;
import universidad1.Conexion;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Usuario
 */
public class AlumnoVista extends javax.swing.JPanel {
    private AlumnoData alumnoData;
    private Conexion conexion;
    public AlumnoVista() {
        initComponents();
        conexion = new Conexion();
        alumnoData = new AlumnoData(conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jif_Alumno = new javax.swing.JInternalFrame();
        jb_TituloAlumno = new javax.swing.JLabel();
        jb_IdAlumno = new javax.swing.JLabel();
        jb_Nombre = new javax.swing.JLabel();
        jb_FechaNac = new javax.swing.JLabel();
        jb_Activo = new javax.swing.JLabel();
        jtf_IdAlumno = new javax.swing.JTextField();
        jtf_Nombre = new javax.swing.JTextField();
        jtf_FechaNacimiento = new javax.swing.JTextField();
        jl_Apellido = new javax.swing.JLabel();
        jtf_Apellido = new javax.swing.JTextField();
        jb_Buscar = new javax.swing.JButton();
        jb_Borrar = new javax.swing.JButton();
        jb_Actualizar = new javax.swing.JButton();
        jb_Guardar = new javax.swing.JButton();
        jb_Limpiar = new javax.swing.JButton();
        jcb_Activo = new javax.swing.JCheckBox();

        jif_Alumno.setClosable(true);
        jif_Alumno.setIconifiable(true);
        jif_Alumno.setMaximizable(true);
        jif_Alumno.setVisible(true);

        jb_TituloAlumno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jb_TituloAlumno.setForeground(new java.awt.Color(0, 0, 225));
        jb_TituloAlumno.setText("-Alumno-");

        jb_IdAlumno.setText("Id Alumno");

        jb_Nombre.setText("Nombre");

        jb_FechaNac.setText("Fecha Nacimiento");

        jb_Activo.setText("Activo");

        jl_Apellido.setText("Apellido");

        jb_Buscar.setText("Buscar");
        jb_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_BuscarActionPerformed(evt);
            }
        });

        jb_Borrar.setText("Borrar");
        jb_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_BorrarActionPerformed(evt);
            }
        });

        jb_Actualizar.setText("Actualizar");
        jb_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ActualizarActionPerformed(evt);
            }
        });

        jb_Guardar.setText("Guardar");
        jb_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_GuardarActionPerformed(evt);
            }
        });

        jb_Limpiar.setText("Limpiar");
        jb_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jif_AlumnoLayout = new javax.swing.GroupLayout(jif_Alumno.getContentPane());
        jif_Alumno.getContentPane().setLayout(jif_AlumnoLayout);
        jif_AlumnoLayout.setHorizontalGroup(
            jif_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jif_AlumnoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jif_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_TituloAlumno)
                    .addGroup(jif_AlumnoLayout.createSequentialGroup()
                        .addGroup(jif_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_Nombre)
                            .addComponent(jb_IdAlumno)
                            .addComponent(jb_FechaNac)
                            .addComponent(jb_Activo)
                            .addComponent(jl_Apellido))
                        .addGroup(jif_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jif_AlumnoLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jif_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_IdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jif_AlumnoLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jif_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcb_Activo)
                                    .addComponent(jtf_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jif_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_Limpiar)
                    .addComponent(jb_Buscar)
                    .addComponent(jb_Actualizar)
                    .addComponent(jb_Borrar)
                    .addComponent(jb_Guardar))
                .addGap(36, 36, 36))
        );
        jif_AlumnoLayout.setVerticalGroup(
            jif_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jif_AlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_TituloAlumno)
                .addGap(32, 32, 32)
                .addGroup(jif_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jif_AlumnoLayout.createSequentialGroup()
                        .addGroup(jif_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_IdAlumno)
                            .addComponent(jtf_IdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_Buscar))
                        .addGap(18, 18, 18)
                        .addGroup(jif_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_Nombre)
                            .addComponent(jtf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_Guardar))
                        .addGap(18, 18, 18)
                        .addGroup(jif_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Apellido)
                            .addComponent(jtf_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_Borrar))
                        .addGap(14, 14, 14)
                        .addGroup(jif_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_FechaNac)
                            .addComponent(jtf_FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_Actualizar))
                        .addGap(18, 18, 18)
                        .addComponent(jb_Activo))
                    .addComponent(jcb_Activo))
                .addGap(18, 18, 18)
                .addComponent(jb_Limpiar)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jif_Alumno)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jif_Alumno)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jb_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_BuscarActionPerformed
        int id = Integer.parseInt(jtf_IdAlumno.getText());
        Alumno a = new Alumno();
        a = alumnoData.buscarAlumno(id);
        if (a != null){
            jtf_IdAlumno.setText(a.getIdAlumno() + "");
            jtf_Nombre.setText(a.getNombre());
            jtf_FechaNacimiento.setText(a.getFechaNac().toString());
            jcb_Activo.setSelected(a.isActivo());
            
        }
    }//GEN-LAST:event_jb_BuscarActionPerformed

    private void jb_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_GuardarActionPerformed
        String nombre = jtf_Nombre.getText();
        String apellido = jtf_Apellido.getText();
        LocalDate fechaNac = LocalDate.parse(jtf_FechaNacimiento.getText(), DateTimeFormatter.ofPattern("yyyy-mm-dd"));
        boolean activo = jcb_Activo.isSelected();
        Alumno a = new Alumno(-1, apellido ,nombre, fechaNac, activo);
        alumnoData.guardarAlumno(a);
        jtf_IdAlumno.setText(a.getIdAlumno() + "");
    }//GEN-LAST:event_jb_GuardarActionPerformed

    private void jb_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_BorrarActionPerformed
        int id = Integer.parseInt(jtf_IdAlumno.getText());
        Alumno a = null;
        a = alumnoData.buscarAlumno(id);
        alumnoData.eliminarAlumno(a);      
    }//GEN-LAST:event_jb_BorrarActionPerformed

    private void jb_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ActualizarActionPerformed
        if (jtf_IdAlumno.getText() != null){
            int id = Integer.parseInt(jtf_IdAlumno.getText());
            String nombre = jtf_Nombre.getText();
            String apellido = jtf_Apellido.getText();
            LocalDate fechaNac = LocalDate.parse(jtf_FechaNacimiento.getText(), DateTimeFormatter.ofPattern("yyyy-mm-dd"));
            boolean activo = jcb_Activo.isSelected();
            Alumno a = new Alumno(id, apellido ,nombre, fechaNac, activo);
            alumnoData.actualizarAlumno(a);
        }
    }//GEN-LAST:event_jb_ActualizarActionPerformed

    private void jb_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_LimpiarActionPerformed
        jtf_Nombre.setText("");
        jtf_Apellido.setText("");
        jtf_IdAlumno.setText("");
        jtf_FechaNacimiento.setText("");
        jcb_Activo.setEnabled(true);
    }//GEN-LAST:event_jb_LimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jb_Activo;
    public javax.swing.JButton jb_Actualizar;
    public javax.swing.JButton jb_Borrar;
    public javax.swing.JButton jb_Buscar;
    public javax.swing.JLabel jb_FechaNac;
    public javax.swing.JButton jb_Guardar;
    public javax.swing.JLabel jb_IdAlumno;
    public javax.swing.JButton jb_Limpiar;
    public javax.swing.JLabel jb_Nombre;
    public javax.swing.JLabel jb_TituloAlumno;
    public javax.swing.JCheckBox jcb_Activo;
    public javax.swing.JInternalFrame jif_Alumno;
    public javax.swing.JLabel jl_Apellido;
    public javax.swing.JTextField jtf_Apellido;
    public javax.swing.JTextField jtf_FechaNacimiento;
    public javax.swing.JTextField jtf_IdAlumno;
    public javax.swing.JTextField jtf_Nombre;
    // End of variables declaration//GEN-END:variables
}
