package vistas;

import universidad1.Conexion;
import universidad1.Materia;
import universidad1.MateriaData;

public class VistaMateria extends javax.swing.JInternalFrame {
    private MateriaData materiaData;
    private Conexion conexion;
    
    public VistaMateria()
    {
        initComponents();
        conexion = new Conexion();
        materiaData = new MateriaData(conexion);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_buscar = new javax.swing.JButton();
        jl_MATERIA = new javax.swing.JLabel();
        jb_borrar = new javax.swing.JButton();
        jb_limpiar = new javax.swing.JButton();
        jtf_id = new javax.swing.JTextField();
        jtf_materia = new javax.swing.JTextField();
        jl_ID = new javax.swing.JLabel();
        jl_NOMBRE = new javax.swing.JLabel();
        jb_guardar = new javax.swing.JButton();
        jb_actualizar = new javax.swing.JButton();

        jb_buscar.setText("BUSCAR");
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });

        jl_MATERIA.setBackground(new java.awt.Color(0, 0, 255));
        jl_MATERIA.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jl_MATERIA.setText("MATERIA");
        jl_MATERIA.setBorder(null);
        jl_MATERIA.setMaximumSize(new java.awt.Dimension(60, 60));
        jl_MATERIA.setMinimumSize(new java.awt.Dimension(60, 60));
        jl_MATERIA.setPreferredSize(new java.awt.Dimension(66, 16));

        jb_borrar.setText("Borrar");
        jb_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_borrarActionPerformed(evt);
            }
        });

        jb_limpiar.setText("Limpiar");
        jb_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limpiarActionPerformed(evt);
            }
        });

        jl_ID.setText("ID");

        jl_NOMBRE.setText("NOMBRE");

        jb_guardar.setText("Guardar");
        jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarActionPerformed(evt);
            }
        });

        jb_actualizar.setText("Actualizar");
        jb_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jb_borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb_limpiar)
                                .addGap(33, 33, 33)
                                .addComponent(jb_actualizar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jl_MATERIA, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(jb_guardar)
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_ID)
                        .addGap(69, 69, 69)
                        .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_NOMBRE)
                        .addGap(29, 29, 29)
                        .addComponent(jtf_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_MATERIA, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_ID)
                    .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_NOMBRE)
                            .addComponent(jtf_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_actualizar)
                            .addComponent(jb_guardar)
                            .addComponent(jb_limpiar)
                            .addComponent(jb_borrar))
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jb_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
        int id = Integer.parseInt(jtf_id.getText());
        Materia mate = new Materia();
        mate = materiaData.buscarMateria(id);

        if (mate != null) {
            jtf_id.setText(mate.getIdMateria() + "");
            jtf_materia.setText(mate.getNombreMateria());

    }//GEN-LAST:event_jb_buscarActionPerformed
    }
        
    private void jb_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_borrarActionPerformed
        int id = Integer.parseInt(jtf_id.getText());
        Materia mate = null;
        mate = materiaData.buscarMateria(id);
        materiaData.eliminarMateria(mate);

    }//GEN-LAST:event_jb_borrarActionPerformed

    private void jb_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limpiarActionPerformed
        jtf_id.setText("");
        jtf_materia.setText("");

    }//GEN-LAST:event_jb_limpiarActionPerformed

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
        String nombreMate = jtf_materia.getText();
        Materia mate = new Materia(-1, nombreMate);
        materiaData.guardarMateria(mate);
        jtf_id.setText(mate.getIdMateria()+"");

    }//GEN-LAST:event_jb_guardarActionPerformed

    private void jb_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_actualizarActionPerformed
        if (jtf_id.getText() != null){
            int id = Integer.parseInt(jtf_id.getText());
            String nombre = jtf_materia.getText();
            Materia mate = new Materia(id, nombre);
            materiaData.actualizarMateria(mate);

    }//GEN-LAST:event_jb_actualizarActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_actualizar;
    private javax.swing.JButton jb_borrar;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_limpiar;
    private javax.swing.JLabel jl_ID;
    private javax.swing.JLabel jl_MATERIA;
    private javax.swing.JLabel jl_NOMBRE;
    private javax.swing.JTextField jtf_id;
    private javax.swing.JTextField jtf_materia;
    // End of variables declaration//GEN-END:variables
}
